version: "3.7"
services: 
  hugo: 
    build: 
      context: ./../
      dockerfile: ./local-test-setup/developer.Dockerfile
      args:
        - atcUsername=${ATC_USERNAME} 
        - atcPassword=${ATC_PASSWORD}
        - target=url-path
    ports: 
      - "1313:1313"
    command: server 
    volumes:
      - ./../:/src/content/docs/url-path
